- name: Set working directory
  ansible.builtin.set_fact:
    k8s_dir: "{{ playbook_dir }}/../k8s"

- name: Apply MySQL Deployment
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    namespace: "{{ k8s_namespace }}"
    src: "{{ k8s_dir }}/mysql-deployment.yaml"
    validate_certs: no

- name: Apply MySQL Service
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    namespace: "{{ k8s_namespace }}"
    src: "{{ k8s_dir }}/mysql-service.yaml"
    validate_certs: no

- name: Wait for MySQL pod to be ready
  shell: kubectl wait --namespace {{ k8s_namespace }} --for=condition=ready pod -l app=mysql --timeout=120s
  register: mysql_status
  failed_when: "'condition met' not in mysql_status.stdout"

- name: Deploy Login Service
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    namespace: "{{ k8s_namespace }}"
    src: "{{ item }}"
    validate_certs: no
  loop:
    - "{{ k8s_dir }}/login-deployment.yaml"
    - "{{ k8s_dir }}/login-service.yaml"

- name: Deploy KeyExchange Service
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    namespace: "{{ k8s_namespace }}"
    src: "{{ item }}"
    validate_certs: no
  loop:
    - "{{ k8s_dir }}/keyexchange-deployment.yaml"
    - "{{ k8s_dir }}/keyexchange-service.yaml"

- name: Deploy Messaging Service
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    namespace: "{{ k8s_namespace }}"
    src: "{{ item }}"
    validate_certs: no
  loop:
    - "{{ k8s_dir }}/messaging-deployment.yaml"
    - "{{ k8s_dir }}/messaging-service.yaml"

- name: Deploy Frontend
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    namespace: "{{ k8s_namespace }}"
    src: "{{ item }}"
    validate_certs: no
  loop:
    - "{{ k8s_dir }}/frontend-deployment.yaml"
    - "{{ k8s_dir }}/frontend-service.yaml"

- name: Deploy Ingress
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    namespace: "{{ k8s_namespace }}"
    src: "{{ k8s_dir }}/ingress.yaml"
    validate_certs: no
