- name: Install Trivy vulnerability scanner on localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install Trivy using official install script
      shell: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      args:
        creates: /usr/local/bin/trivy

    - name: Verify Trivy installation
      command: trivy --version
      register: trivy_version
      changed_when: false

    - debug:
        msg: "{{ trivy_version.stdout }}"

- name: Scan Docker images for vulnerabilities
  hosts: localhost
  connection: local
  become: no
  vars:
    docker_images:
      - iharshal/frontend:latest
      - iharshal/login:latest
      - iharshal/keyexchange:latest
      - iharshal/messaging:latest
      - mysql:8
  tasks:
    - name: Scan image with Trivy
      command: >
        trivy image --severity HIGH,CRITICAL --exit-code 1 {{ item }}
      loop: "{{ docker_images }}"
      register: trivy_scan_results
      ignore_errors: yes

    - name: Show scan result for image
      debug:
        msg: |
          Image {{ item.item }} scan result:
          {{ item.stdout }}
      loop: "{{ trivy_scan_results.results }}"

